
module.exports = {

  q_Id_One: {
    max: 'optionA',
    taylor: 'optionB',
    riley: 'optionC',
    jackson: 'optionD',
    sab: 'optionB',
    levi: 'optionA',
    daniel: 'optionC',
  },
  q_Id_Two: {
    max: 'optionA',
    taylor: 'optionA',
    riley: 'optionB',
    jackson: 'optionB',
    sab: 'optionB',
    levi: 'optionA',
    daniel: 'optionD',
  },
  q_Id_Three: {
    max: 'optionB',
    taylor: 'optionB',
    riley: 'optionD',
    jackson: 'optionA',
    sab: 'optionC',
    levi: 'optionC',
    daniel: 'optionC',
  },
  q_Id_Four: {
    max: 'optionA',
    taylor: 'optionB',
    riley: 'optionC',
    jackson: 'optionA',
    sab: 'optionA',
    levi: 'optionD',
    daniel: 'optionB',
  },
  q_Id_Five: {
    max: 'optionA',
    taylor: 'optionB',
    riley: 'optionD',
    jackson: 'optionA',
    sab: 'optionB',
    levi: 'optionB',
    daniel: 'optionA',
  },
  q_Id_Six: {
    max: 'optionA',
    taylor: 'optionB',
    riley: 'optionB',
    jackson: 'optionB',
    sab: 'optionB',
    levi: 'optionC',
    daniel: 'optionA',
  },
  q_Id_Seven: {
    max: 'optionB',
    taylor: 'optionC',
    riley: 'optionC',
    jackson: 'optionC',
    sab: 'optionA',
    levi: 'optionB',
    daniel: 'optionA',
  }
};